### ISSUE TITLE
pika spack spec with `+stdexec`, `nvhpc@24.9` and `gcc@14.2.0` doesn't concretize

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#1264]

**Comment by msimberg** [comment]
Indeed, the conflict comes from `cuda` and `gcc`, not `nvhpc` and `gcc`. Specifically: https://github.com/spack/spack/blob/8a9bfd162d32675dcd0de002b47325bc4db1e0fc/lib/spack/spack/build_systems/cuda.py#L166 (i.e. GCC 14 can't be used with any version of CUDA at the moment).
