### ISSUE TITLE
Fix handling of `value_types` and `error_types` with references in all sender adaptors

### ISSUE THREAD

**Issue by msimberg** [pika-org/pika#284]
See #282 for details.

These need to be checked and fixed if necessary:

- [x] `bulk` (#338)
- [x] `drop_value` (#338)
- [x] `ensure_started` (#338)
- [x] `let_error` (#338, #371)
- [x] `let_value` (#472)
- [x] `split` (#285)
- [x] `start_detached` (#474)
- [x] `sync_wait` (#285)
- [x] `then` (#338)
- [x] `transfer` (#338)
- [x] `when_all` (#320)
- [ ] `when_all_vector` (#484)

**Comment by aurianer** [comment]
"partially" in resolving an issue is not taken into account with bors anymore?

**Comment by msimberg** [comment]
It never did, and bors doesn't do anything about closing issues. That's all GitHub.

**Comment by aurianer** [comment]
Yes indeed as you pointed out I switched the position of partially and fixed, so it doesn't work in this order

**Comment by msimberg** [comment]
For reference, this is the syntax used for automatically closing issues: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword.
