### ISSUE TITLE
Investigate segfaults in MacOS Arm64 workflow

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#471]
Investigate seg faults from the tests that have been excluded from the MacOS Arm64 workflow in #469. Listed here: https://github.com/pika-org/pika/blob/89fdaa20caa3f95c59dbe02cbdd0a287c3d21acc/.github/workflows/macos_arm64_debug.yml#L64-L70.

**Comment by msimberg** [comment]
We no longer use the M1 workflow in CI. https://github.com/pika-org/pika/issues/1095 may revive it, but until then I'm closing this issue.
