### ISSUE TITLE
Only hello_world_test is run when PIKA_WITH_TESTS=ON PIKA_WITH_TESTS_UNIT=ON

### ISSUE THREAD

**Issue by yurivict** [pika-org/pika#473]
I know that before pika was running hundreds of tests, but now it only runs one test.

Something is missing in the system, and configure doesn't complain.
Maybe cmake upgrade to 3.24.0 caused this?

Versions: 0.8.0, 0.9.0
cmake-3.24.0
FreeBSD 13.1

**Comment by msimberg** [comment]
Could you post more explicit logs of how you're building and running the tests please?

**Comment by msimberg** [comment]
I think this is no longer an issue. Likely same issue as #853. Please reopen if that's not the case.
