### ISSUE TITLE
Fix memory leak reported by sanitizers

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#497]
## Expected Behavior

No memory leak

## Actual Behavior

```
$  ./bin/os_thread_num 
OS-thread 2 ran 33 PX-threads
OS-thread 0 ran 32 PX-threads
OS-thread 1 ran 32 PX-threads
OS-thread 3 ran 31 PX-threads

=================================================================
==1739870==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 88 byte(s) in 1 object(s) allocated from:
    #0 0x4a497d in malloc (/build/pika/build_asan/bin/os_thread_num+0x4a497d)
    #1 0x7f2ae9797a8c in lt__malloc (/lib/x86_64-linux-gnu/libltdl.so.7+0x2a8c)

SUMMARY: AddressSanitizer: 88 byte(s) leaked in 1 allocation(s).
```

## Steps to Reproduce the Problem

... Please be as specific as possible while describing how to reproduce your problem.

  #. Source .jenkins/cscs/env-clang-11.sh
  #. Configured with `cmake -GNinja $configure_extra_options -DPIKA_WITH_EXAMPLES=ON -DPIKA_WITH_SANITIZERS=ON -DCMAKE_CXX_FLAGS="-fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer" <pika_repo>`
  #. Run ./bin/os_thread_num

## Specifications

... Please describe your environment

This problem doesn't appear on daint with the env-clang-11.sh spack CI environment
  - pika version (commit/tag): main
  - Platform (OS, compiler, etc.): Ubuntu 20.04 with Clang-11

**Comment by msimberg** [comment]
I think we can close this. At least I have not seen this on the new sanitizer CI configurations. We can reopen if it comes up again.
