### ISSUE TITLE
Attempt to enforce use of lock-free 128-bit atomics with GCC when supported

### ISSUE THREAD

**Issue by msimberg** [pika-org/pika#575]
Currently it seems like GCC/libatomic may fall back to mutexes for 128-bit atomics, even with `-mcx16` set. This can have very bad consequences for performance since the default queue uses 128-bit atomics.

Clang happily seems to use intrinsics when compiling with `-mcx16`.

Platforms where they aren't supported should obviously not be forced to use them.

**Comment by barracuda156** [comment]
Make sure not to enforce those on 32-bit platforms, where libatomic supports up to 64-bit atomics. And then, linking to libatomic is required, which is currently broken: https://github.com/pika-org/pika/issues/576

**Comment by msimberg** [comment]
I think we can close this. While we haven't changed anything to force the use of lockfree 128-bit atomics, we've instead changed many queues to default to the moodycamel queue which only uses 64-bit atomics which I haven't seen any issues with. See e.g. #1023, #1033, #924.
