### ISSUE TITLE
Explicit linking to libatomic is required on 32-bit platforms

### ISSUE THREAD

**Issue by barracuda156** [pika-org/pika#576]
GCC does not link to `libatomic` automatically. On 32-bit platforms passing `-latomic` flag is required.

```
-- Performing Test PIKA_WITH_CXX11_ATOMIC - Failed
-- Test failed, detailed output:

Change Dir: /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_pika/pika/work/build/CMakeFiles/config_tests/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_67881/fast && /usr/bin/make  -f CMakeFiles/cmTC_67881.dir/build.make CMakeFiles/cmTC_67881.dir/build
Building CXX object CMakeFiles/cmTC_67881.dir/cxx11_std_atomic.cpp.o
/opt/local/bin/mpicxx-mpich-gcc12   -pipe -I/opt/local/libexec/boost/1.76/include -Os -DNDEBUG -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -Werror   -arch ppc -mmacosx-version-min=10.6 -std=c++17 -o CMakeFiles/cmTC_67881.dir/cxx11_std_atomic.cpp.o -c /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_devel_pika/pika/work/pika-0.11.0/cmake/tests/cxx11_std_atomic.cpp
Linking CXX executable cmTC_67881
/opt/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_67881.dir/link.txt --verbose=1
/opt/local/bin/mpicxx-mpich-gcc12 -pipe -I/opt/local/libexec/boost/1.76/include -Os -DNDEBUG -I/opt/local/libexec/boost/1.76/include -I/opt/local/include -D_GLIBCXX_USE_CXX11_ABI=0 -Werror   -arch ppc -mmacosx-version-min=10.6 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/local/libexec/boost/1.76/lib -L/opt/local/lib -Wl,-headerpad_max_install_names  CMakeFiles/cmTC_67881.dir/cxx11_std_atomic.cpp.o -o cmTC_67881 
Undefined symbols:
  "___atomic_store_8", referenced from:
      _main in cxx11_std_atomic.cpp.o
  "___atomic_load_8", referenced from:
      _main in cxx11_std_atomic.cpp.o
ld: symbol(s) not found
```

**Comment by msimberg** [comment]
Thanks @barracuda156 for pointing this out.

Just to explain this and the behaviour you're seeing in https://github.com/pika-org/pika/issues/575#issuecomment-1407780410, for historical reasons we have two feature tests, one for "regular" atomics (i.e. up to 8-byte atomics) which we've always assumed would either be there or be hopelessly broken; and another test for 16-byte atomics which we first try to detect without `libatomic`, and if that fails we retry the test with `libatomic`. If _that_ doesn't work then we're done and can't do much more.

That said, I think we could just have a single feature test for all atomics, and do the fallback-to-libatomic dance for that... it should work for all types of atomics.

**Comment by msimberg** [comment]
@barracuda156 would you mind trying #580? I think it's ok, but I don't have a 32-bit system to test it on definitively.

**Comment by barracuda156** [comment]
> @barracuda156 would you mind trying #580? I think it's ok, but I don't have a 32-bit system to test it on definitively.

Sure, I will update you within an hour or so. Running tests on the build now.
