### ISSUE TITLE
Fix ICE in `cuda_sender_test` with ROCm Clang-15

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#585]
Compiler error: https://cdash.cscs.ch/test/66321134. Triggered by triggered by the call to `vm.count("seed")` (https://github.com/pika-org/pika/blob/87b10a0b70973cbaf164c46118444839501e0d56/libs/pika/async_cuda/tests/unit/cuda_sender.cu#L129).

**Comment by msimberg** [comment]
This doesn't seem to be an issue anymore.
