### ISSUE TITLE
Potential bug in `thread_pool_scheduler`

### ISSUE THREAD

**Issue by msimberg** [pika-org/pika#60]
Try to see if this can be reproduced: https://app.circleci.com/pipelines/github/pika-org/pika/133/workflows/00b0996c-601f-4f6c-8f1c-f3b533738a4a/jobs/1462/steps?invite=true#step-103-164.

**Comment by msimberg** [comment]
I've not been able to reproduce this some removing this from 0.3.0, but @aurianer and @biddisco please keep an eye out if you see the `thread_pool_scheduler` test fail again in some configuration and we can try to return to this.

**Comment by aurianer** [comment]
I've also seen that in the gcc-10 config (https://cdash.cscs.ch/test/7568537)
