### ISSUE TITLE
Make sure `PIKA_PROCESS_MASK` is actually honored by the runtime configuration

### ISSUE THREAD

**Issue by msimberg** [pika-org/pika#743]
https://github.com/pika-org/pika/pull/739#discussion_r1295965920

Also make sure to add documentation about `PIKA_PROCESS_MASK`.

**Comment by RMeli** [comment]
I did not comment on time on #751, but I think that that once this is fixed it would be good to add a mention of `PIKA_PROCESS_MASK` to the documentation, in addition to `--pika:process-mask`.

**Comment by msimberg** [comment]
> I did not comment on time on #751, but I think that that once this is fixed it would be good to add a mention of `PIKA_PROCESS_MASK` to the documentation, in addition to `--pika:process-mask`.

Absolutely. I left it out of #751 on purpose because of this issue, but we should add it once it works reliably.
