### ISSUE TITLE
Fix the segfault happening on CSCS CI for `tests.unit.modules.executors.std_thread_scheduler`

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#777]
Segfault happening on CSCS CI configuration with pika-ci-image:
https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/479009878135925/5304355110917878/-/jobs/5110101781

**Comment by msimberg** [comment]
Closing this as #784 was merged. The test does at least not seem to fail _every_ run. The test is still listed in #191 so it's not completely ignored if it keeps failing occasionally.
