### ISSUE TITLE
Adapt cross compilation architecture for the CI compiler stage

### ISSUE THREAD

**Issue by aurianer** [pika-org/pika#988]
We currently build the compiler for the arch it will run on (broadwell if daint-mc) and not for the arch the build stage is happening on (zen2 on rosa). We need to figure out how to adapt it for Grace-Hopper.

**Comment by msimberg** [comment]
From discussions it seems like this will not be needed. Instead there will be for each compute node architecture a corresponding build farm, so cross-compilation isn't required. I'll close this for now and if we find out we need it after all we can reopen it.
